### ISSUE TITLE
Ignore_globs not working

### ISSUE THREAD

**Issue by Sof0-0** [microsoft/DevSkim-Action#24]
Hello, so I have been testing various options for DevSkim Action and the "ignore-globs" seems to not be working, as I have been trying to ignore specific files, however, they are being tested anyway. Is there any way to fix that?

I would appreciate it!

**Comment by gfs** [comment]
Sorry you're having trouble with the ignore globs. Can you provide an example the globs you're using that aren't working?

**Comment by Sof0-0** [comment]
Sure, I tried any path I could think of (am I understanding correctly that we include the file format that we want to ignore during scan?):
"./*.*" or "*.*" or "./*.sh, */*.sh" (to ignore shell files). Any option I tried was still included in the scan.

**Comment by gfs** [comment]
Those don't look like the right format for file globs for me. If you want to match any .sh file you would want `**/.sh`. 

For example, `/.sh` would only match a file named `.sh` in the root of the file system.

You can test globs using an online tool like this one: https://www.digitalocean.com/community/tools/glob.

**Comment by Sof0-0** [comment]
<img width="215" alt="Screenshot 2024-03-11 at 16 42 33" src="https://github.com/microsoft/DevSkim-Action/assets/104607214/fb88c006-c1eb-4ea1-a205-41087c2d1cad">
I tried multiple globs, and even the example you provided does not exclude those files during the scan (I gave the example of the ones that are scanning in root on purpose as I was trying to ignore those first but they are being scanned anyway).
<img width="560" alt="Screenshot 2024-03-11 at 16 42 09" src="https://github.com/microsoft/DevSkim-Action/assets/104607214/9075ae61-a6f3-4ced-9d27-705758fbbc11">

**Comment by gfs** [comment]
Sorry, that's my error in the example. It should have been `**/*.sh`.  

`**` for any preceding directory structure
`*` for any string
`.sh` ending in .sh.

**Comment by gfs** [comment]
As for ignoring files in the root, you can add a task to print out the location the source gets checked out into, it should match the pipeline variable `GITHUB_WORKSPACE` variable (I don't think that specifying this variable as part of the globs will work), but in my experience it is not the root of the file system and is subject to change. https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

**Comment by Sof0-0** [comment]
So to be precise, what does the globs variable allow us to ignore? Because yes, I have used the example you showed, and those files are still included in the scan. It just gives the same results (does not exclude any files with that format)

**Comment by gfs** [comment]
The globs argument is passed to the `--ignore-globs` argument of the DevSkim CLI application being executed by the DevSkim-Action in [entrypoint.sh](https://github.com/microsoft/DevSkim-Action/blob/b41921d947434b27f90b8949f8bfbe056e706bf6/entrypoint.sh#L40). 

Inside the devskim application, each file path is checked against the provided globs using [Microsoft.Extensions.FileSystemGlobbing](https://learn.microsoft.com/en-us/dotnet/core/extensions/file-globbing). If the file path matches one of the globs it will not be scanned.

**Comment by gfs** [comment]
I've now had a chance to test this in the action and can confirm it's not working as intended. The wildcard arguments are being lost between the yml and the entrypoint. The globbing functionality in the CLI does appear to be working as intended so the issue is somewhere in the github action specification.

**Comment by gfs** [comment]
Thanks for your report. I have a fix pending in #25 that should resolve this. It looks like the issue was Bash automatically expanding the globs before they were passed to devskim.
