### ISSUE TITLE
sarif results are not displayed under "security" tab

### ISSUE THREAD

**Issue by chipitsine** [microsoft/DevSkim-Action#6]
I enabled DevSkim action: https://github.com/chipitsine/haproxy/runs/3919514372?check_suite_focus=true
scan is performed, I added sarif result to artifacts.

however, I do not see any reported issue under "security" tab.

where should I report it ?

**Comment by chipitsine** [comment]
"chipitsine/haproxy" is public fork.
I can add you as repo admin if you wish

**Comment by gfs** [comment]
I can see it now. 

Works in the browser but I tried to open it in the GitHub app.

**Comment by gfs** [comment]
It looks like we need to update devskim to include some field mentioned here: https://github.com/github/codeql-action/issues/665
