### ISSUE TITLE
files are not displayed properly on github

### ISSUE THREAD

**Issue by chipitsine** [microsoft/DevSkim-Action#7]
for example: https://github.com/chipitsine/haproxy/security/code-scanning/23?query=ref%3Arefs%2Fheads%2Fmaster

![image](https://user-images.githubusercontent.com/2217296/137850520-978dc872-39c8-4bf2-8006-9d601acb4221.png)

I guess it might be because of "workspace" in path. shouldn't it be removed ?

**Comment by chipitsine** [comment]
another question - the above finding is documentation. I do not think it worth being scanned. How any bugs from documentation can affect us ?

shouldn't documentation (i.e. "*.txt" files) be skipped by default ?

or can I skip them manually ?

**Comment by gfs** [comment]
> another question - the above finding is documentation. I do not think it worth being scanned. How any bugs from documentation can affect us ?
> 
> 
> 
> shouldn't documentation (i.e. "*.txt" files) be skipped by default ?

This rule does appear to be written to only apply to code (though code of any language). Offhand I don't think we have a distinction between code and documentation. Just code and comment, and if something isn't a comment it's considered code. Since .txt doesn't have defined comment extensions the snippet here wouldn't be commented and would thus be "code". 

At the very least I'll add an option so you can provide some extensions to skip. 

> 
> 
> 
> or can I skip them manually ?

You can manually mark the issue as non relevant.

**Comment by chipitsine** [comment]
> > another question - the above finding is documentation. I do not think it worth being scanned. How any bugs from documentation can affect us ?
> > shouldn't documentation (i.e. "*.txt" files) be skipped by default ?
> 
> This rule does appear to be written to only apply to code (though code of any language). Offhand I don't think we have a distinction between code and documentation. Just code and comment, and if something isn't a comment it's considered code. Since .txt doesn't have defined comment extensions the snippet here wouldn't be commented and would thus be "code".
> 
> At the very least I'll add an option so you can provide some extensions to skip.
> 
> > or can I skip them manually ?
> 
> You can manually mark the issue as non relevant.

there are trillions of "TLS" in txt files. can I skip entire "doc" folder in some DevSkim settings ?

also, txt does not appear to be language of any kind, I still think it might be whitelisted entirely
